OnlineStore/Areas/Admin/Controllers/HomeAdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using OnlineStore.Controllers;
using OnlineStore.Infrastructure.Interfeices;
using SmartBreadcrumbs.Attributes;

namespace OnlineStore.Areas.Admin.Controllers
{
    /// <summary>
    /// Главный контроллер области администрации
    /// </summary>
    [Area("Admin"), Authorize(Roles = Domain.Entities.UserEntities.User.RoleAdmin)]
    public class HomeAdminController : Controller
    {
        private readonly IProductData productData;

        public HomeAdminController(IProductData productData)
        {
            this.productData = productData;
        }

        /// <summary>
        /// Стартовая страница области администратора
        /// </summary>
        /// <returns></returns>
        [Breadcrumb("Область администратора")]
        public IActionResult Index() => View();

        /// <summary>
        /// Внутренняя страница области администратора
        /// </summary>
        /// <returns></returns>
        [Breadcrumb("Информация", FromAction = "Index", FromController = typeof(HomeAdminController))]
        public IActionResult Info() => View();

    }

}

OnlineStore/Areas/Admin/Views/HomeAdmin/Index.cshtml
@{
    ViewData["Title"] = "Администратор";
    Layout = "_LayoutAdminArea";
}

<h2>@ViewData["Title"]</h2>

<br />
<div class="row text-center pad-top">
    <div class="col-lg-2 col-md-2 col-sm-2 col-xs-6">
        <div class="div-square">
            <a asp-area="Admin" asp-controller="ProductList" asp-action="Index">
                <i class="fa fa-circle-o fa-5x"></i>
                <h4>Список товаров</h4>
            </a>
        </div>
    </div>   
    <div class="col-lg-2 col-md-2 col-sm-2 col-xs-6">
        <div class="div-square">
            <a asp-area="Admin" asp-controller="Employee" asp-action="Index">
                <i class="fa fa-users fa-5x"></i>
                <h4>Сотрудники</h4>
            </a>
        </div>
    </div>
    <div class="col-lg-2 col-md-2 col-sm-2 col-xs-6">
        <div class="div-square">
            <a asp-area="Admin" asp-controller="HomeAdmin" asp-action="Info">
                <i class="fa fa-key fa-5x"></i>
                <h4>Администратор </h4>
            </a>
        </div>

    </div>  
</div>

OnlineStore/Areas/Admin/Views/HomeAdmin/Info.cshtml
@{
    ViewData["Title"] = "Администратор";
    Layout = "_LayoutAdminArea";
}

<h2>Информация</h2>