OnlineStore/Areas/Admin/ViewModels/ProductListViewModel.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using OnlineStore.Domain.Entities.ProductsEntities;
using OnlineStore.ViewModels;
using OnlineStore.ViewModels.Common;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace OnlineStore.Areas.Admin.ViewModels
{
    public class ProductListViewModel
    {
        public ProductFilter productFilter { get; set; }
        public SelectList Sections { get; set; }        

        public SelectList Categories { get; set; }

        public List<BrandViewModel> Brands{ get; set; }

        public List<ProductViewModel> Products { get; set; }

        public SortViewModelForProduct SortViewModel { get; set; }

        public PageViewModel PageViewModel { get; set; }

        public ProductListViewModel() { }

       
    }
}

OnlineStore/Areas/Admin/Controllers/ProductListController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using OnlineStore.Areas.Admin.ViewModels;
using OnlineStore.Domain.Entities.ProductsEntities;
using OnlineStore.Domain.SortsEntities;
using OnlineStore.Infrastructure.Interfeices;
using OnlineStore.Infrastructure.Mappers;
using OnlineStore.ViewModels;
using OnlineStore.ViewModels.Common;
using OnlineStore.ViewModels.Product;
using SmartBreadcrumbs.Attributes;

namespace OnlineStore.Areas.Admin.Controllers
{
    /// <summary>
    /// Контроллер для работы с товарами 
    ///  Позволяет просматривать, редактировать, загружать и удалять
    ///  </summary>
    [Area("Admin"), Authorize(Roles = Domain.Entities.UserEntities.User.RoleAdmin)]
    public class ProductListController : Controller
    {
        private readonly IProductData productData;

        public IHostingEnvironment appEnvironment;

        public ProductListController(IProductData productData, IHostingEnvironment appEnvironment)
        {
            this.productData = productData;
            this.appEnvironment = appEnvironment;
        }


        /// <summary>
        /// Страница с перечнем товаров
        /// </summary>
        /// <returns></returns>
        [Breadcrumb("Список товаров", AreaName = "Admin", FromAction = "Index", FromController = typeof(HomeAdminController))]
        public async Task<IActionResult> Index(string Name, List<int> Brands, string JsonBrands, int? SecID, int? CatID, decimal? MinP, decimal? MaxP,
            string sortValue = SortEntityForProducts.NameAsc, int page = 1, bool needChangeSort = true)
        {
            //Временный листинг ID выбранных брендов
            var brandsID = new List<int>();

            //Определим откуда пришли данные, из тагхелпера сортировки или из формы фильтра
            if ((Brands == null || Brands.Count == 0) && !String.IsNullOrEmpty(JsonBrands))
            {
                brandsID = JsonConvert.DeserializeObject<List<int>>(JsonBrands);
            } //распарсиваем Json в листинг брендов
            else { brandsID = Brands; }

            //ФИЛЬМТРАЦИЯ ДАННЫХ
            //Получаем лист товаров по заданному фильтру
            ProductFilter productFilter = new ProductFilter {Name =Name, SectionId = SecID, CategoryId = CatID, BrandIdCollection = brandsID, MinPrice = MinP, MaxPrice = MaxP };
                              

            //Выборка товаров по фильтру
            var products = productData.GetProducts(productFilter);

         
            //СОРТИРОВКА ДАННЫХ
            //сортировка списка товаров
            //Сохраним текущую сортировку если это необходимо
            if (!needChangeSort)
                sortValue = SaveSort(sortValue);

            switch (sortValue)
            {
                case SortEntityForProducts.NameDes:
                    products = products.OrderByDescending(s => s.Name);
                    break;

                case SortEntityForProducts.BrandAsc:
                    products = products.OrderBy(s => s.Brand);
                    break;

                case SortEntityForProducts.BrandDes:
                    products = products.OrderByDescending(s => s.Brand);
                    break;


                case SortEntityForProducts.SectionAsc:
                    products = products.OrderBy(s => s.Brand);
                    break;

                case SortEntityForProducts.SectionDes:
                    products = products.OrderByDescending(s => s.Brand);
                    break;

                case SortEntityForProducts.CategoryAsc:
                    products = products.OrderBy(s => s.Brand);
                    break;

                case SortEntityForProducts.CategoryDes:
                    products = products.OrderByDescending(s => s.Brand);
                    break;

                case SortEntityForProducts.PriceAsc:
                    products = products.OrderBy(s => s.Price);
                    break;

                case SortEntityForProducts.PriceDes:
                    products = products.OrderByDescending(s => s.Price);
                    break;

                default:
                    products = products.OrderBy(s => s.Name);
                    break;
            }

            //ПАГИНАЦИЯ ДАННЫХ
            //Пагинация
            int pageSize = 12;//размер страницы
            var count = await products.CountAsync();//количество единиц товаров
            var PageProducts = await products.Skip((page - 1) * pageSize).Take(pageSize).ToListAsync();//количество страниц


            var sections = await productData.GetSections().ToListAsync();          
            sections.Insert(0, new Section { Name = "Все", id = 0 });
            var categories = await productData.GetCategories(null).ToListAsync();
            categories.Insert(0, new Category { Name = "Все", id = 0 });

            var brands = await productData.GetBrands(null).ToListAsync();
            var BrandsViewModels = brands.Select(brand => brand.CreateViewModel()).ToList();
            for (int i = 0; i < BrandsViewModels.Count; i++)
            {
                if (productFilter.BrandIdCollection.Contains(BrandsViewModels[i].Id))
                    BrandsViewModels[i].Choosen = true;
            }

            //Заполняем данныe для ViewModel с товарами
            var productListViewModel = new ProductListViewModel
            {
                productFilter = productFilter,               
                Products = PageProducts.Select(ProductViewModelMapper.CreateViewModel).ToList(),              
                PageViewModel = new PageViewModel(count, page, pageSize),
                SortViewModel = new SortViewModelForProduct(sortValue),
                Sections = new SelectList(sections, "id", "Name"),
                Categories = new SelectList(categories, "id", "Name"),
                Brands = BrandsViewModels
            };

            return View(productListViewModel);
        }

        /// <summary>
        /// Подробный просмотр информации о товаре
        /// </summary>
        /// <returns></returns>
        [Authorize(Roles = Domain.Entities.UserEntities.User.RoleAdmin)]
        [Breadcrumb("Подробно", FromAction = "Index", FromController = typeof(HomeAdminController))]
        public async Task<IActionResult> Details(int id)
        {
            //ProductViewModel productViewModel = new ProductViewModel();
            var product = await Task.Run(()=> productData.GetProductById(id));
            var productViewModel = product.CreateViewModel();

            if (productViewModel is null)
                return NotFound();

            return View(productViewModel);
        }

        /// <summary>
        /// Просмотр товара с вожможностью редактирования
        /// </summary>
        /// <param name="id">id товара</param>
        /// <returns></returns>
        [Authorize(Roles = Domain.Entities.UserEntities.User.RoleAdmin)]
        [Breadcrumb("Редактировать", FromAction = "Index", FromController = typeof(HomeAdminController))]
        public async Task<IActionResult> Edit(int? idProduct, int? idImage)
        {
           
            //emp_view_model.Positions = new SelectList(positions, "id", "Name", emp_view_model.Position.id);

            ProductViewModel productViewModel;
           
            if (idProduct != null)
            {
                if (idProduct > 0)
                {
                    var product = await Task.Run(() => productData.GetProductById(idProduct));
                    productViewModel = product.CreateViewModel();
                    if (productViewModel is null)
                        return NotFound();
                }//товар уже есть в каталоге
                else
                {
                    productViewModel = new ProductViewModel();
                    productViewModel.Id = 0;
                }//новый товар, с временным  ID=0, товар уже есть в представлении, но еще нет в базе

                if (idImage != null)
                {
                    productViewModel.Image = productData.GetFileById(Convert.ToInt32(idImage));
                }//присвоить новое изображение
            }//уже существующий товар
            else
            {
                productViewModel = new ProductViewModel();
            }//новый товар

            var sections = await productData.GetSections().ToListAsync();
            var selectedSection = productViewModel.Section != null ? productViewModel.Section.id : 1;

            var categories = await productData.GetCategories(null).ToListAsync();
            var selectedCategory = productViewModel.Category != null ? productViewModel.Category.id : 1;

            var brands = await productData.GetBrands(null).ToListAsync();
            var selectedBrand = productViewModel.Brand != null ? productViewModel.Brand.id : 1;


            productViewModel.Sections = new SelectList(sections, "id", "Name", selectedSection);
            productViewModel.Categories = new SelectList(categories, "id", "Name", selectedCategory);
            productViewModel.Brands = new SelectList(brands, "id", "Name", selectedBrand);

            return View(productViewModel);
        }

        /// <summary>
        /// Отправка отредактированной формы товара в базу
        /// </summary>
        /// <param name="id">id товара</param>
        /// <returns></returns>
        [Authorize(Roles = Domain.Entities.UserEntities.User.RoleAdmin)]
        [HttpPost]
        public IActionResult Edit(ProductViewModel productView)
        {
            if (!ModelState.IsValid) return View(productView);
            var product = productView.CreateProduct();                        

OnlineStore/Areas/Admin/Views/ProductList/ChangeImageForProduct.cshtml
@model OnlineStore.Areas.Admin.ViewModels.ImagesCatalogViewModel

@{
    ViewData["Title"] = "Изменить изображение";
    Layout = "_LayoutAdminArea";
}

<hr />
<h3>Выберите файл для загрузки</h3>
<form asp-action="UploadFiles" asp-route-idproduct="@Model.IdProduct" asp-controller="ProductList" method="post" enctype="multipart/form-data">
    <input type="file" name="uploadedFile" /><br>
    @*<a class="btn" asp-area="Admin" asp-controller="ProductList" asp-action="ChangeImageForProduct" asp-route-id="@Model.IdProduct">*@
    <input type="submit" value="Загрузить" />
    </a>
</form>
<hr />

<div class="container">
    <b>Все изображение в каталоге</b><br>
    @foreach (var img in Model.Images)
    {
        <div class="col-sm-4">
            <div class="product-image-wrapper">
                <div class="single-products">
                    <div class="productinfo text-center">
                        <p><a asp-area="Admin" asp-controller="ProductList" asp-action="Edit" asp-route-idimage="@img.id" asp-route-idproduct="@Model.IdProduct"> <img src="@img.Path" alt="@img.Name" /></a></p>
                    </div>
                </div>
            </div>
        </div>
    }
</div>

OnlineStore/Areas/Admin/Views/ProductList/Details.cshtml
@model OnlineStore.ViewModels.ProductViewModel

@{
    ViewData["Title"] = "Детально";
    Layout = "_LayoutAdminArea";
}

<h2>@ViewData["Title"]</h2>
<hr />

<div class="row">
    <div class="col-md-4 col-md-offset-4">
        <div>
            <b>Секция</b>
            <p class="fa-border alert-danger">
                @Model.Section.Name
            </p>
        </div>
        <div>
            <b>Категория</b>
            <p class="fa-border alert-danger">
                @Model.Category.Name
            </p>
        </div>
        <div>
            <b>Бренд</b>
            <p class="fa-border alert-danger">
                @Model.Brand.Name
            </p>
        </div>
        <div>
            <b>Название</b>
            <p class="fa-border alert-danger">
                @Model.Name
            </p>
        </div>    
        <div>
            <b>Цена</b>
            <p class="fa-border alert-danger">
                @Model.Price
            </p>
        </div>
        <div class="container">
            <img src="@Model.Image.Path" alt="">
        </div>
        <div>
            <input type="button" onclick="history.go(-1)" value="Назад" />
        </div>
        <div>
            <br />
        </div>
    </div>
</div>
<hr />

OnlineStore/Areas/Admin/Views/ProductList/Edit.cshtml
@model OnlineStore.ViewModels.ProductViewModel
@{
    ViewData["Title"] = "Редактирование";
    Layout = "_LayoutAdminArea";
}

<h2>@ViewData["Title"]</h2>

<hr />

<div class="row">
    <div class="col-md-4 col-md-offset-4">
        <form method="post" asp-area="Admin" asp-controller="ProductList" asp-action="Edit">

            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <input asp-for="Id" type="hidden" />



            <div>
                @Html.LabelFor(model => model.Sections)
                @Html.DropDownListFor(model => model.Section.id, Model.Sections as SelectList,
                        htmlAttributes: new { @class = "form-control" })
            </div>

            <div>
                @Html.LabelFor(model => model.Categories)
                @Html.DropDownListFor(model => model.Category.id, Model.Categories as SelectList,
                        htmlAttributes: new { @class = "form-control" })
            </div>

            <div>
                @Html.LabelFor(model => model.Brands)
                @Html.DropDownListFor(model => model.Brand.id, Model.Brands as SelectList,
                        htmlAttributes: new { @class = "form-control" })
            </div>

            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>

            <input asp-for="Image.id" type="hidden" />

            <div class="form-group">
                <div class="container">
                    @if (Model.Id != null)
                    {
                        <img src="@Model.Image.Path" alt="">
                    }
                    <br>
                    <br>
                    <a class="btn" asp-area="Admin" asp-controller="ProductList" asp-action="ChangeImageForProduct" asp-route-idproduct="@Model.Id">Изменить изображение</a>
                </div>
            </div>

            <div class="form-group">
                <input type="submit" value="Сохранить" class="btn btn-default" />
            </div>
        </form>

        <div>
            <a asp-area="Admin" asp-controller="ProductList" asp-action="Index">Вернуться к списку товаров</a>
        </div>

        <div>
            <br />
        </div>

    </div>
</div>


@section Scripts{
    @await Html.PartialAsync("_ValidationScriptsPartial")
}

OnlineStore/Areas/Admin/Views/ProductList/Index.cshtml
@model OnlineStore.Areas.Admin.ViewModels.ProductListViewModel
@using OnlineStore.Domain.SortsEntities
<!--Пользовательский TagHelper-->
@addTagHelper "*, OnlineStore"

@{
    ViewData["Title"] = "Список товаров";
    Layout = "_LayoutAdminArea";
}

@{
    var routedata = new Dictionary<string, string>();
    routedata.Add("SecID", Model.productFilter.SectionId.ToString());
    routedata.Add("CatID", Model.productFilter.CategoryId.ToString());
    routedata.Add("Name", Model.productFilter.Name);
    if (Model.productFilter.BrandIdCollection != null && Model.productFilter.BrandIdCollection.Count > 0)
    {
        var JsonCollection = Html.Raw(Json.Serialize(Model.productFilter.BrandIdCollection));
        routedata.Add("JsonBrands", JsonCollection.ToString());
    }
}

<h2>@ViewData["Title"]</h2>

<hr />
<div>
    <a asp-controller="HomeAdmin" asp-action="Index" class="btn btn-default">Назад</a>
</div>

<br />

<a asp-area="Admin" asp-controller="ProductList" asp-action="Edit" class="btn btn-default">Добавить товар</a>

<hr />

@*ФИЛЬТРАЦИЯ ДАННЫХ*@
<form  asp-area="Admin" asp-controller="ProductList" asp-action="Index">
    <ul class="list-inline">
        <li>
            <label class="control-label">Наименование товара: </label>
            @Html.TextBox("Name", Model.productFilter.Name, htmlAttributes: new { @class = "form-control" })
        </li>
        <li>
            <label class="control-label">Секции: </label>
            @Html.DropDownList("SecID", Model.Sections as SelectList,
                    htmlAttributes: new { @class = "form-control" })
        </li>
        <li>
            <label class="control-label">Категории: </label>
            @Html.DropDownList("CatID", Model.Categories as SelectList,
                    htmlAttributes: new { @class = "form-control" })
        </li>

        <li class="dropdown">
            <a href="#" data-toggle="dropdown" class="btn bt">
                <b>Выбрать Бренд</b><b class="caret"></b>
            </a>           
            <ul class="dropdown-menu pre-scrollable">

                @for (int i = 0; i < Model.Brands.Count; i++)
                {
                    <li style="white-space:nowrap">
                        @if (Model.Brands[i].Choosen)
                        {
                            <input type="checkbox" name="Brands"
                                    id="@Model.Brands[i].Id" value="@Model.Brands[i].Id"
                                    class="styled" checked>}
                        else
                        { <input type="checkbox" name="Brands"
                                    id="@Model.Brands[i].Id" value="@Model.Brands[i].Id"
                                    class="styled">}

                        <label>@Model.Brands[i].Name </label>
                    </li>
                }
            </ul>     

        </li>
    </ul>
    <hr />
    <button type="submit" class="btn btn-primary">Фильтр</button>
    <a asp-controller="ProductList" asp-action="Index" asp-area="Admin" class="btn btn-primary">Очистить фильтр</a>
</form>

<br />

@*ДАННЫЕ*@
<table class="table table-striped">
    <thead>
        <tr>
            <th></th>
            <th>
                <sort action-name="Index" controller-name="ProductList" area-name="Admin" up="@Model.SortViewModel.Up" current="@Model.SortViewModel.Current" route-data="@routedata"
                      property="@Model.SortViewModel.NameSort">
                    Название
                </sort>
            </th>
            <th>
                <sort action-name="Index" controller-name="ProductList" area-name="Admin" up="@Model.SortViewModel.Up" current="@Model.SortViewModel.Current" route-data="@routedata"
                      property="@Model.SortViewModel.SectionSort">
                    Секция
                </sort>
            </th>
            <th>
                <sort action-name="Index" controller-name="ProductList" area-name="Admin" up="@Model.SortViewModel.Up" current="@Model.SortViewModel.Current" route-data="@routedata"
                      property="@Model.SortViewModel.CategorySort">
                    Категория
                </sort>
            </th>>
            <th>
                <sort action-name="Index" controller-name="ProductList" area-name="Admin" up="@Model.SortViewModel.Up" current="@Model.SortViewModel.Current" route-data="@routedata"
                      property="@Model.SortViewModel.BrandSort">
                    Бренд
                </sort>
            </th>
            <th>
                <sort action-name="Index" controller-name="ProductList" area-name="Admin" up="@Model.SortViewModel.Up" current="@Model.SortViewModel.Current" route-data="@routedata"
                      property="@Model.SortViewModel.PriceSort">
                    Цена
                </sort>
            </th>

            <th>Изображение </th>
            <th>Просмотреть</th>
            @if (User.IsInRole("Administrator"))
            {
                <th>Удалить из базы</th>
            }

        </tr>
    </thead>
    <tbody>
        @foreach (var product in Model.Products)
        {
        <tr>
            <td><a asp-area="Admin" asp-controller="ProductList" asp-action="Edit" asp-route-idproduct="@product.Id"><i class="fa fa-edit"></i></a></td>
            <td>@product.Name</td>
            <td>@product.Section.Name</td>
            <td>@product.Category.Name</td>
            <td>@product.Brand.Name</td>
            <td>@product.Price</td>
            <td> <img src="@product.Image.Path" height="100" width="100" alt=""></td>
            <td><a asp-area="Admin" asp-controller="ProductList" asp-action="Details" asp-route-id="@product.Id">Подробно</a></td>
            @if (User.IsInRole("Administrator"))
            {
                <td><a asp-area="Admin" asp-controller="ProductList" asp-action="Delete" asp-route-id="@product.Id"><i class="fa fa-times text text-danger" /></a></td>
            }
        </tr>
        }
    </tbody>
</table>
<div>
    @{
        routedata.Add("sortValue", Model.SortViewModel.Current);
        routedata.Add("needChangeSort", "false");
    }
    <page-link page-model="Model.PageViewModel" action-name="Index" controller-name="ProductList" area-name="Admin" route-data="routedata"></page-link>
</div>